services:
  jira:
    image: atlassian/jira-software:9.12.1
    container_name: jira
    ports:
      - "8089:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=2048m
    depends_on:
      - db
    volumes:
      - jira_data:/var/atlassian/application-data/jira

  db:
    image: postgres:13
    container_name: postgres-jira
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
      POSTGRES_DB: jiradb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  jira_data:
  postgres_data:
